name: Test

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests with coverage
        run: bun test --coverage

      - name: Build
        run: bun run build

  coverage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check 100% coverage
        run: |
          bun test --coverage > coverage.txt 2>&1 || true
          cat coverage.txt
          
          # Extract coverage percentage and check if it's 100%
          if ! grep -E "All files\s+\|\s+100\.00\s+\|\s+100\.00" coverage.txt; then
            echo "❌ Coverage is not 100%"
            echo "Please ensure all code is covered by tests"
            exit 1
          fi
          
          echo "✅ Coverage is 100%"

